import {
  BarChart3,
  Brain,
  Calendar,
  Coins,
  Compass,
  Cpu,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  Landmark,
  Lock,
  Megaphone,
  Palette,
  RefreshCw,
  Rocket,
  Scale,
  ShieldCheck,
  Shirt,
  Sparkles,
  Target,
  TrendingUp,
  Truck,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Registro de íconos disponibles para los pasos del reto (ver src/data/questions.ts). */
export const iconMap: Record<string, LucideIcon> = {
  brain: Brain,
  chart: BarChart3,
  calendar: Calendar,
  coins: Coins,
  compass: Compass,
  cpu: Cpu,
  gamepad: Gamepad2,
  globe: Globe,
  graduation: GraduationCap,
  heart: Heart,
  landmark: Landmark,
  lock: Lock,
  megaphone: Megaphone,
  palette: Palette,
  refresh: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  shield: ShieldCheck,
  shirt: Shirt,
  sparkles: Sparkles,
  target: Target,
  trending: TrendingUp,
  truck: Truck,
  users: Users,
  wrench: Wrench,
  zap: Zap,
};

export const getIcon = (name: string): LucideIcon => iconMap[name] ?? Sparkles;
